AWSTemplateFormatVersion: "2010-09-09"
Description: Create a test VPC
Parameters: 

  # define the area parameters for subnet
  az1nameParameters: 
    Description: please select first AvailabilityZone Name for 0&1 subnet
    Type: "AWS::EC2::AvailabilityZone::Name"
  az2nameParameters: 
    Description: please select second AvailabilityZone Name for 2&3 subnet
    Type: "AWS::EC2::AvailabilityZone::Name"
  testVpc:
    Description: VPC
    Type: "AWS::EC2::VPC::Id"
  public0:
    Description: public 0
    Type: "AWS::EC2::Subnet::Id"
  public2:
    Description: public2
    Type: "AWS::EC2::Subnet::Id"
  CertificateArn:
    Description: The HTTPS Certificates Arn
    Type: CommaDelimitedList
    Default: "arn:aws:acm:ap-northeast-2:510338692548:certificate/39f4695d-20df-4641-9b90-e9a0d66f1316"
  testElbSecGroup:
    Description: ELB SEC Group
    Type: List<AWS::EC2::SecurityGroup::Id>
  testElbTargetGroup:
    Description: testElbTargetGroup
    Type: String
    Default: arn:aws:elasticloadbalancing:ap-northeast-2:510338692548:targetgroup/testTargetGroup/c6f2d21cc999211c
  testElb:
    Description: test ELB
    Type: String
    Default: arn:aws:elasticloadbalancing:ap-northeast-2:510338692548:loadbalancer/app/testElb/99e8e9bcc338d0b7
  testRedisSecGroup:
    Description: Redis SEC Group
    Type: List<AWS::EC2::SecurityGroup::Id>
  testRedisSubnet:
    Description: Redis Subnet
    Type: String
    Default: testredissubnetgroup
  testRdsSecGroup:
    Description: RDS SecurityGroup
    Type: List<AWS::EC2::SecurityGroup::Id>
  testRdsSubnet:
    Description: RDS Subnet
    Type: String
    Default: testRdsSubnetGroup
  testEc2SecGroup:
    Description: EC2 SecurityGroup
    Type: List<AWS::EC2::SecurityGroup::Id>
  testElbTargetGroup:
    Description: TargetGroupARNs
    Type: CommaDelimitedList
    Default: "arn:aws:elasticloadbalancing:ap-northeast-2:510338692548:targetgroup/testTargetGroup/c6f2d21cc999211c,"

Resources:
  testAutoScall:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: testAS
      AvailabilityZones:
        Fn::GetAZs: 
          Ref: "AWS::Region"
      LaunchConfigurationName: testLauConfig
      MaxSize: "3"
      MinSize: "1"