AWSTemplateFormatVersion: "2010-09-09"
Description: gitlab-ee
Resources:
  MyEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties: 
      ImageId: "ami-007b2c3a7b3239792"
      InstanceType: t2.medium
      KeyName: aws-shouer-gitlab
      BlockDeviceMappings:
        -
          DeviceName: /dev/sda1
          Ebs:
            VolumeType: io1
            Iops: 200
            DeleteOnTermination: false
            VolumeSize: 10