AWSTemplateFormatVersion: "2010-09-09"
Description: Create a VPC
Resources:
  testVpc:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: 192.168.0.0/16
      EnableDnsSupport: false
      EnableDnsHostnames: false
      InstanceTenancy: default